# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Npm@1
  inputs:
    command: 'publish'
    verbose: true
    publishRegistry: 'useFeed'
    publishFeed: 'da11ffaa-cef1-4788-9980-340b6a6f8763/1c7cf5fd-a5a7-493d-ac04-7a024b0aa7ef'
